export const assetsMap = {
    'USD': 'United States dollar',
    'CNY': 'China Yuan',
    'GBP': 'Great Britain Pound',
    'JPY': 'Japanese Yen',
    'CAD': 'Canadian Dollar',
    'SGD': 'Singapore Dollar',
    'CNH': 'Offshore RMB',
    'NZD': 'New Zealand dollar',
    'AUD': 'Australian Dollar',
    'CHF': 'Confederation Helvetica Franc',
    'HKD': 'Hong Kong Dollar',
    'EUR': 'European Monetary Unit',
    'BSV': 'Bitcoin SV',
    'BTC': 'BitCoin',
    'ETH': 'Ethereum',
    'BNB': 'Binance Coin',
    'USDT': 'Tether',
    'REEF': 'Reef Finance',
    'SAND': 'The Sandbox',
    'LINK': 'ChainLink',
    'BTT': 'BitTorrent',
    'DASH': 'Dash',
    'RACA': 'Radio Caca',
    'SHIB': 'Shiba Inu',
    'ATOM': 'Cosmos',
    'GALA': 'Gala',
    'AAVE': 'Aave',
    'MANA': 'Decentraland',
    'XMR': 'Monero',
    'XLM': 'Stellar',
    'ADA': 'Cardano',
    'XTZ': 'Tezos',
    'WBTC': 'Wrapped Bitcoin',
    'VET': 'Vechain',
    'UNI': 'Uniswap',
    'XRP': 'Ripple',
    'SOL': 'Solana',
    'TRX': 'TRON',
    'OKB': 'OKB',
    'THETA': 'Theta',
    'OMG': 'OMG Network',
    'MATIC': 'Polygon',
    'NEO': 'Neo',
    'FTT': 'FTX Token',
    'FIL': 'Filecoin',
    'LTC': 'Litecoin',
    'DOT': 'Polkadot NEW',
    'DOGE': 'Dogecoin',
    'BCH': 'Bitcoin Cash',
    'IOTA': 'MIOTA',
    'EOS': 'EOS',
    'AXS': 'Axie Infinity',
    'AVAX': 'Avalanche',
    'DYDX': 'dYdX'
}
